### PR TITLE
[Menu] Fix menu display

### LINKED ISSUE #6: [Menu/Panel] Make the subMenu in front of panels by default.
_From @rodolpheV on October 18, 2016 14:16_
# Current behaviour

layout_css_submenu_in_back
# Expected behaviour

layout_css_submenu_in_front
## Versions

focus-components@3.0.0-rc18

_Copied from original issue: KleeGroup/focus-components#1281_

### LINKED ISSUE #7: [Menu] Let the possibility to choose icon library of buttons
_From @rodolpheV on October 18, 2016 13:42_
# Current behaviour

Only material icon works.
# Expected behaviour

Authorize the props iconLibrary: 'font-custom'.
## Versions

Focus-components@3.0.0-rc18

_Copied from original issue: KleeGroup/focus-components#1280_

### PR DESCRIPTION
**Pull request by TomGallon**
## Fix

Fixes #6 : Menu relative position with other components
Fixes #7 : Now possible to user another lib than material
## Enhancement

Remove useless LinkComponent props. Add peer dependency to react-router.

### CODE REVIEW

File: src/menu/index.js [hunk 1]
```diff
@@ -153,11 +151,11 @@ class Menu extends Component {
             <nav data-focus='menu' data-size={size}>
                 <div>
                     <div data-focus='menu-brand' data-click={!!handleBrandClick} onClick={() => handleBrandClick && handleBrandClick()} />
-                    <MenuList activeMenuId={activeMenuId} menus={menus} LinkComponent={LinkComponent} showLabels={showLabels} showPanel={showPanel} onClick={::this._onSelectMenu} />
+                    <MenuList activeMenuId={activeMenuId} menus={menus} showLabels={showLabels} showPanel={showPanel} onClick={::this._onSelectMenu} />
                     {children}
```
Comment (Ephrame) [inline src/menu/index.js:158]: It's not a good method to bind a function

**Review by Ephrame — APPROVED** [review]
