### PR TITLE
[select-mdl] Fix select-mdl values

### LINKED ISSUE #24: [selectMdl] no refresh
# Current behaviour

When the component receive newProps values, it doesn't update. 

# Expected behaviour

It will update.

### PR DESCRIPTION
**Pull request by GuenoleK**
### Description

This update fix the fact the component doesn't get the given datas in the options. 
I have additionally updated the props which were never used (allValues for example) from the constructor.

I have a problem, when i click in an option, the menu doesn't hide. I have checked, the div with `mdl-menu__container is-upgraded` have a `is-visible` class which should be removed by mdl when we click on the option element which is an `li`.
It only has the good behaviour when we click on an undefined option.

I don't really where it is from mdl or react/redux @TomGallon @Ephrame 

> Fixes #24

### CODE REVIEW

File: src/select/index.js [hunk 1]
```diff
@@ -72,6 +72,7 @@ class Select extends PureComponent {
     render() {
         const { autoFocus, error, multiple, name, placeholder, style, rawInputValue, values, disabled, onChange, size, valid } = this.props;
         const selectProps = { autoFocus, disabled, multiple, size };
+        console.log(this.props);
```
Comment (TomGallon) [inline src/select/index.js]: console.log to remove.
